/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GenTable {
        "source": string;
        "subject": string;
    }
}
declare global {
    interface HTMLGenTableElement extends Components.GenTable, HTMLStencilElement {
    }
    var HTMLGenTableElement: {
        prototype: HTMLGenTableElement;
        new (): HTMLGenTableElement;
    };
    interface HTMLElementTagNameMap {
        "gen-table": HTMLGenTableElement;
    }
}
declare namespace LocalJSX {
    interface GenTable {
        "source"?: string;
        "subject"?: string;
    }
    interface IntrinsicElements {
        "gen-table": GenTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gen-table": LocalJSX.GenTable & JSXBase.HTMLAttributes<HTMLGenTableElement>;
        }
    }
}
